/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/api-cloudflare/wrangler-ingress.jsonc --include-runtime=false --env-interface=GatewayEnv apps/api-cloudflare/ingress-configuration.d.ts` (hash: 63acac08f74c7d9d690b3b0d30f3d1d5)
interface __BaseEnv_GatewayEnv {
  HYPERBUG_INGRESS_KEY: string;
  API:
    | Fetcher /* hyperbug-api-staging */
    | Fetcher /* hyperbug-api */
    | Fetcher /* hyperbug-api-local */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/ingress');
  }
  interface StagingEnv {
    HYPERBUG_INGRESS_KEY: string;
    API: Fetcher /* hyperbug-api-staging */;
  }
  interface ProductionEnv {
    HYPERBUG_INGRESS_KEY: string;
    API: Fetcher /* hyperbug-api */;
  }
  interface Env extends __BaseEnv_GatewayEnv {}
}
interface GatewayEnv extends __BaseEnv_GatewayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'HYPERBUG_INGRESS_KEY'>
  > {}
}
